Resources:
  AWSEBAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchTemplate:
        LaunchTemplateName: !Sub "${AWSEBEnvironmentName}-LT"
        Version: !GetAtt AWSEBAutoScalingLaunchTemplate.LatestVersionNumber
